@BASE_URL = http://localhost:3000
@name = paul
@password = abcd1234
@displayName = Paul
@JWT = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBsaWNhdGlvbl9pZCI6IjE5ZTA0NjViLTdjZDktNGU3ZS05NmQ4LWM3OTQyYTliZGI4NyIsImlhdCI6MTYxNTgyMDg0MjY1OSwianRpIjoiYzVhNjdjZDktNTZlNC00YWJmLWE0NjgtYThlYjkzN2M1ZTMxIiwic3ViIjoicGF1bCIsInVzZXJfaWQiOiJVU1ItNDQzMjZkMDQtY2Q4Mi00MWY1LWFkMjQtMzE1YzJhMmVhYzQxIiwiZXhwIjoxNjE1OTA3MjQzLCJhY2wiOnsicGF0aHMiOnsiLyovdXNlcnMvKioiOnt9LCIvKi9jb252ZXJzYXRpb25zLyoqIjp7fSwiLyovc2Vzc2lvbnMvKioiOnt9LCIvKi9kZXZpY2VzLyoqIjp7fSwiLyovaW1hZ2UvKioiOnt9LCIvKi9tZWRpYS8qKiI6e30sIi8qL2FwcGxpY2F0aW9ucy8qKiI6e30sIi8qL3B1c2gvKioiOnt9LCIvKi9rbm9ja2luZy8qKiI6e319fX0.DCCOffXEXe8eDCrGW5a7vwslyhf1dxUT7ChV9USHEXnv5PVyFXZJNtQrYMuZh3mJ5l-sJJJLtkGs159zn1yCH8n-VG2X_6IrmpMUe8VqdZK58Gk2iFXX69R6u1PvDurMkdI_lhZ_W9qxU5EoDWZiL3YuU0_1SfWMMvoMJ4f-LG3ekfWu-LCBKB-FcNiUKuYiqqKD7TEXPv7JJm7ruTdJ3rp-GmNwcfAYyn4g_CNnQTbUWi2DFePXZHz0KdIoV8z4J4j2rcJWgFiWxKH950RhXAsvhoOKqx25KQJ7KBDlG3NE4S74ULTCcFqmkf8kjMIcX3iuVMPb0K9DqUG6B8o1gA
@CONV_ID = CON-3f2e0470-e913-478a-b489-7b93caacd907


### SIGNUP
post {{BASE_URL}}/signup HTTP/1.1
Content-Type: application/json

{ "name": "{{name}}", "password": "{{password}}", "display_name": "{{displayName}}" }

### LOGIN
post http://localhost:3000/login
Content-Type: application/json

{ "name": "{{name}}", "password": "{{password}}"}


###  LIST OF USERS
get http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer {{JWT}}


###  LIST OF CONVERSATIONS (inc. member)
get http://localhost:3000/conversations
Content-Type: application/json
Authorization: Bearer {{JWT}}


###  RETRIEVE A CONVERSATION (inc. members & events)
get http://localhost:3000/conversations/{{CONV_ID}}
Content-Type: application/json
Authorization: Bearer {{JWT}}


###  CREATE A CONVERSATION
post http://localhost:3000/conversations
Content-Type: application/json
Authorization: Bearer {{JWT}}

{ "users": [
  "USR-43462453-b3be-4e01-9d3c-5f2525bc79d5"
]}

