### MEMBER INVITED
post http://localhost:3000/rtc/events HTTP/1.1
Content-Type: application/json

{
  "type": "member:invited",
  "from": "MEM-1e9f4633-ceba-4052-8fe6-4d138cc45535",
  "conversation_id": "CON-3f2e0470-e913-478a-b489-7b93caacd907",
  "body":{
    "cname":"Testing twitch 3",
    "conversation":{
      "conversation_id":"CON-3f2e0470-e913-478a-b489-7b93caacd907",
      "name":"Testing twitch 3"
    },
    "user":{
      "member_id":"MEM-1e9f4633-ceba-4052-8fe6-4d138cc45535",
      "user_id":"USR-a73915a7-cc68-4600-96f9-402c1ec3ab59",
      "media":{
        "audio_settings":{
          "enabled":false,
          "earmuffed":false,
          "muted":false
        },
        "audio":{
          "enabled":false,
          "earmuffed":false,
          "muted":false
        }
      },
      "name":"Todd-97b0453d-c6a3-4b8d-b3a9-721c4a865780",
      "display_name":"Pres. Ivory Watsica"
    },
    "channel":{
      "type":"app","legs":[],"leg_ids":[]
    },
    "media":{
      "audio_settings":{"enabled":false,"earmuffed":false,"muted":false},
      "audio":{"enabled":false,"earmuffed":false,"muted":false}
    },
    "timestamp":{
      "invited":"2021-02-15T15:41:29.110Z"
    },
    "initiator":{"invited":{"isSystem":true}}
  },
  "id":4,
  "application_id":"19e0465b-7cd9-4e7e-96d8-c7942a9bdb87",
  "timestamp":"2021-02-15T15:41:29.112Z"
}



### MEMBER JOINED
post http://localhost:3000/rtc/events HTTP/1.1
Content-Type: application/json

{
  "type":"member:joined",
  "from": "MEM-1e9f4633-ceba-4052-8fe6-4d138cc45535",
  "conversation_id":"CON-3f2e0470-e913-478a-b489-7b93caacd907",
  "body":{
    "user":{
      "id":"USR-0d38d443-31ef-4c26-ba1e-e709cae71618",
      "user_id":"USR-0d38d443-31ef-4c26-ba1e-e709cae71618",
      "name":"Tyrell-f085f60b-6e42-47b7-813e-3b154bd7bf7e",
      "display_name":"Lorene Volkman"
    },
    "channel":{"type":"app","legs":[],"leg_settings":{},"leg_ids":[]},
    "timestamp":{
      "invited":"2021-02-15T15:39:29.132Z",
      "joined":"2021-02-15T15:47:13.022Z"
    },
    "initiator":{"invited":{"isSystem":true},"joined":{"isSystem":true}}
  },
  "id":6,
  "application_id":"19e0465b-7cd9-4e7e-96d8-c7942a9bdb87",
  "timestamp":"2021-02-15T15:47:13.025Z"
}



### MEMBER LEFT
post http://localhost:3000/rtc/events HTTP/1.1
Content-Type: application/json

{
  "type":"member:left",
  "from": "MEM-1e9f4633-ceba-4052-8fe6-4d138cc45535",
  "conversation_id":"CON-3f2e0470-e913-478a-b489-7b93caacd907",
  "body":{
    "timestamp":{
      "invited":"2021-02-15T15:39:29.132Z",
      "joined":"2021-02-15T15:47:13.022Z",
      "left":"2021-02-18T16:07:57.727Z"
    },
    "user":{
      "id":"USR-0d38d443-31ef-4c26-ba1e-e709cae71618",
      "name":"Tyrell-f085f60b-6e42-47b7-813e-3b154bd7bf7e"
    },
    "channel":{"type":"app","legs":[],"leg_settings":{},"leg_ids":[]},
    "initiator":{"invited":{"isSystem":true},"joined":{"isSystem":true},"left":{"isSystem":true}}
  },
  "id":7,
  "application_id":"19e0465b-7cd9-4e7e-96d8-c7942a9bdb87",
  "timestamp":"2021-02-18T16:07:57.729Z"
}

