@BASE_URL = http://localhost:3000

@name = paul
@password = abcd1234
@displayName = Paul

post {{BASE_URL}}/signup HTTP/1.1
Content-Type: application/json

{ "name": "{{name}}", "password": "{{password}}", "display_name": "{{displayName}}" }

###

post http://localhost:3000/login
Content-Type: application/json

{ "name": "{{name}}", "password": "{{password}}"}

###